version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
      POSTGRES_DB: supplydb
    volumes:
      - supplydb_data:/var/lib/postgresql/data
    ports:
      - "4000:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  rabbitmq:
    image: rabbitmq:3.11-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    command: [ "redis-server", "--requirepass", "5432" ]
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "5432", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./supply-backend
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${spring_datasource_url}
      SPRING_DATASOURCE_USERNAME: ${spring_datasource_username}
      SPRING_DATASOURCE_PASSWORD: ${spring_datasource_password}
      SPRING_RABBITMQ_HOST: ${spring_rabbitmq_host}
      SPRING_RABBITMQ_PORT: ${spring_rabbitmq_port}
      SPRING_RABBITMQ_USERNAME: ${spring_rabbitmq_username}
      SPRING_RABBITMQ_PASSWORD: ${spring_rabbitmq_password}
      SPRING_DATA_REDIS_HOST: ${spring_data_redis_host}
      SPRING_DATA_REDIS_PORT: ${spring_data_redis_port}
      SPRING_DATA_REDIS_PASSWORD: ${spring_data_redis_password}
    ports:
      - "8080:8080"
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
        
  message-service:
    build: ./email-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_RABBITMQ_HOST: ${spring_rabbitmq_host}
      SPRING_RABBITMQ_PORT: ${spring_rabbitmq_port}
      SPRING_RABBITMQ_USERNAME: ${spring_rabbitmq_username}
      SPRING_RABBITMQ_PASSWORD: ${spring_rabbitmq_password}
    ports:
      - "8081:8081"
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  scheduled-service:
    build: ./scheduled-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${spring_datasource_url}
      SPRING_DATASOURCE_USERNAME: ${spring_datasource_username}
      SPRING_DATASOURCE_PASSWORD: ${spring_datasource_password}
      SPRING_RABBITMQ_HOST: ${spring_rabbitmq_host}
      SPRING_RABBITMQ_PORT: ${spring_rabbitmq_port}
      SPRING_RABBITMQ_USERNAME: ${spring_rabbitmq_username}
      SPRING_RABBITMQ_PASSWORD: ${spring_rabbitmq_password}
    ports:
      - "8082:8082"
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  app-network:
    driver: bridge

volumes:
  supplydb_data:

# TODO: create kibernetes deployment config