spring.application.name=scheduled-service

spring.datasource.url=${spring_datasource_url}
spring.datasource.username=${spring_datasource_username}
spring.datasource.password=${spring_datasource_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.rabbitmq.host=${spring_rabbitmq_host}
spring.rabbitmq.port=${spring_rabbitmq_port}
spring.rabbitmq.username=${spring_rabbitmq_username}
spring.rabbitmq.password=${spring_rabbitmq_password}
