apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: supply-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          command: ["redis-server", "--requirepass", "5432"]
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command: ["redis-cli", "-a", "5432", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "-a", "5432", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 128Mi
              cpu: 100m