apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: supply-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: message-service
          image: "ghcr.io/supplydevelopment/email-service:latest"
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: spring_rabbitmq_host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: spring_rabbitmq_port
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: spring_rabbitmq_username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: spring_rabbitmq_password
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 200m