apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: supply-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: app
          image: "ghcr.io/supplydevelopment/supply-backend:latest"
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db:5432/supplydb"
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: "5432"
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              value: "5432"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1024Mi
              cpu: 1000m
            requests:
              memory: 512Mi
              cpu: 500m