apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduled-service
  namespace: supply-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduled-service
  template:
    metadata:
      labels:
        app: scheduled-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: scheduled-service
        image: "ghcr.io/supplydevelopment/scheduled-service:latest"
        envFrom:
          - secretRef:
              name: app-secrets
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: spring_datasource_url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: spring_datasource_username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: spring_datasource_password
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: spring_rabbitmq_host
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: spring_rabbitmq_port
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: spring_rabbitmq_username
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: spring_rabbitmq_password
        ports:
        - containerPort: 8082
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 200m