spring.application.name=email-service

spring.rabbitmq.host=${spring_rabbitmq_host}
spring.rabbitmq.port=${spring_rabbitmq_port}
spring.rabbitmq.username=${spring_rabbitmq_username}
spring.rabbitmq.password=${spring_rabbitmq_password}
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=10000
spring.rabbitmq.listener.simple.retry.max-attempts=2
spring.rabbitmq.listener.direct.retry.max-attempts=2

spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=${mail_username}
spring.mail.password=${mail_password}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true